version: '3.2'

networks:
  integration-test:

services:
  it_tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    environment:
      TOKEN: November 10, 2009
      DATABASE_URL: postgres://hvltiken:BPScY3ULeyMPTm2JIjDnpTEXJeJ14_6A@tiny.db.elephantsql.com/hvltiken
      PORT: :2565
    volumes:
      - .:/go/src/target
    depends_on:
      - db
    networks:
      - integration-test
  db:
    image: postgres:12.12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: go-db
    restart: on-failure
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - integration-test
    