version: '3.2'

networks:
  integration-test:

services:
  go_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      TOKEN: November 10, 2009
      DATABASE_URL: postgres://hvltiken:BPScY3ULeyMPTm2JIjDnpTEXJeJ14_6A@tiny.db.elephantsql.com/hvltiken
      PORT: :2565
    networks:
      - integration-test
    ports:
      - "2565:2565"
  it_test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - .:/go/src/target
    environment:
      TOKEN: November 10, 2009
      DATABASE_URL: postgres://hvltiken:BPScY3ULeyMPTm2JIjDnpTEXJeJ14_6A@tiny.db.elephantsql.com/hvltiken
    